
<h1 style="text-align: center"><u>MANUALES DEL SISTEMA</u></h1>

<table class="general" summary="Datos Bancarios " style="width:25%">
    <tbody>
        <tr>
            <th>Manual de Usuario</th><br>
        </tr>
        <tr>
            <td align="center"><a href="<?php echo $this->baseUrl('public/manual.pdf'); ?>" target="_blank" title="Descargar Manual de Usuario"><?php echo $this->img('ico_archivo_pdf.png'); ?></a></td>
        </tr>
    </tbody>
</table>

<h3 align="center">Al seleccionar <?php echo $this->img('ico_archivo_pdf.png'); ?> el manual se abrirá en una nueva pestaña</h3>
