<div class="container-fluid" align="center">

    <h3 align="center"><u>Detalle del trabajador desde <b><?php echo $this->fecha_desde ?></b> hasta <b><?php echo $this->fecha_hasta ?></b></u></h3>
    <?php echo $this->partial('infotrabajador.phtml', array('trabajador' => $this->datosTrabajador)); ?>
    
    <br>
    
    <div class="row" style="width: 75%;">  
        <table id="tblAsistencia" class="table general table-striped table-bordered table-condensed table-hover">
            <thead>
                <tr>
                    <th style="text-align: center;">Día</th>
                    <th style="text-align: center;">Fecha</th>
                    <th style="text-align: center;">Hora</th>
                    <th style="text-align: center;">Localidad</th>
                    <!-- <th style="text-align: center;">ID Dispositivo</th> -->
                    <th style="text-align: center;">Desc. Dispositivo</th>
                    <th style="text-align: center;">Evento</th>
                    <!-- <th style="width: 8%; text-align: center;" colspan="3">Acción</th> -->
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>

</div>


<script type="text/javascript">
    
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
      "date-uk-pre": function ( a ) {
          var ukDatea = a.split('-');
          return (ukDatea[2] + ukDatea[1] + ukDatea[0]) * 1;
      },

      "date-uk-asc": function ( a, b ) {
          return ((a < b) ? -1 : ((a > b) ? 1 : 0));
      },

      "date-uk-desc": function ( a, b ) {
          return ((a < b) ? 1 : ((a > b) ? -1 : 0));
      }
    });
    
    $(document).ready(function() {
        <?php 
            if (count($this->datosAsistencia) > 0) {
                $var = 'var arrData = [';

                foreach ($this->datosAsistencia as $row) {
                    $var .= "{
                        dia: '{$row->dia}', 
                        fecha: '{$row->fecha}',
                        fecha_completa: '{$row->fecha_completa}',
                        localidad: '{$row->localidad}', 
                        descripcion: '{$row->descripcion}',
                        evento: '{$row->evento}'                           
                    },";
                }          

                $var .= '];';

                echo $var;
            } else {
                echo 'var arrData = [];';
            }
        ?>
                

        $('#tblAsistencia').DataTable({
            dom: "<'row' B l f r><'row' t><'row' i p>",
            buttons: {
                buttons: [
                    {
                        className: 'btn btn-primary',
                        text: '<?php echo $this->img('ico_volver.png'); ?><b> VOLVER</b>',
                        action: function ( e, dt, node, config ) {
                            history.back();
                        }
                    },
                    { 
                        className: 'dt-button',
                        text: 'GENERAR EXCEL',
                        extend: 'excelHtml5', 
                        footer: true , 
                        title: '<?php echo '(SIGRH) Detalle de Asistencia de '.$this->datosTrabajador->nombre.' desde '.$this->fecha_desde.' hasta '.$this->fecha_hasta;?>',
                        exportOptions: { 
                            columns: [ 0, 1, 2, 3, 4, 5] 
                        }
                    }
                ],   
                dom: {
                    button: {
                        tag: "button",
                        className: null
                    }
                }
            },
            language: {
                emptyTable: 'La consulta no devolvió registros.'
            },         
            paging:   true,
            pageLength: 10,
            data: arrData,
            columns: [     
                {
                    data: 'dia',
                    className: 'text-center',
                    render: function (data, type, row, meta) {
                        if(data.toString().trim() == 'monday'){return 'LUN';} 
                        if(data.toString().trim() == 'tuesday'){return 'MAR';} 
                        if(data.toString().trim() == 'wednesday'){return 'MIE';} 
                        if(data.toString().trim() == 'thursday'){return 'JUE';} 
                        if(data.toString().trim() == 'friday'){return 'VIE';}
                        if(data.toString().trim() == 'saturday'){return 'SAB';} 
                        if(data.toString().trim() == 'sunday'){return 'DOM';}
                        return data;
                    }
                },             
                {
                    data: 'fecha',
                    className: 'text-center',
                    type: 'date-uk'
                },   
                {
                    data: 'fecha_completa',
                    className: 'text-center',
                    type: 'date-euro', 
                    render: function (data, type, row) {
                        return moment(data).format('hh:mm:ss A');
                    },
                }, 
                {
                    data: 'localidad',
                    className: 'text-center'
                },   
                {
                    data: 'descripcion',
                    className: 'text-left'
                }, 
                {
                    data: 'evento',
                    className: 'text-left'
                },                  
            ],
            order: [
                [ 1, "asc" ],
                [ 2, "asc" ]
            ]
        });

    });
</script>

