<?php
echo $this->form->renderForm(false);
?>
<fieldset>
    <legend><?php echo $this->form->getLegend(); ?></legend>
    <table class="no-print" align="center" summary="Fomulario">
    <tr>
        <th><?php echo $this->form->getElement(Application_Form_SolicitudAdjunto::E_ADJUNTO)->getLabel(); ?></th>
        <td><?php echo $this->form->getElement(Application_Form_SolicitudAdjunto::E_ADJUNTO)->renderFile(); ?></td>
        <td><?php echo $this->form->getElement(Application_Form_SolicitudAdjunto::E_AGREGAR)->renderViewHelper(); ?></td>
        <td><?php echo $this->form->getElement(Application_Form_SolicitudAdjunto::E_CANCELAR)->renderViewHelper(); ?></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->form->getElement(Application_Form_SolicitudAdjunto::E_ADJUNTO)->renderDescription(),
                       $this->form->getElement(Application_Form_SolicitudAdjunto::E_ADJUNTO)->renderErrors(); ?></td>
        <td></td>
        <td></td>
    </tr>
    </table>
</fieldset>
<table class="general" summary="Listado de Solicitudes">
    <caption>LISTADO DE ARCHIVOS ADJUNTOS - SOLICITUD <?php echo $this->formatoSolicitud($this->form->getSolicitud()->id); ?>
        <span style="float: right;"><?php echo $this->form->getElement(Application_Form_SolicitudAdjunto::E_ELIMINAR)->renderViewHelper();?></span>
    </caption>
    <thead>
        <tr>
            <th width="5%"><?php echo $this->form->getElement(Application_Form_SolicitudAdjunto::E_SELECCION)->renderViewHelper(); ?></th>
            <th>Nombre</th>
            <th width="10%">Tamaño</th>
            <th width="30%">Tipo MIME</th>
            <th width="12%">Fecha de Registro</th>            
        </tr>
    </thead>
    <tbody>
<?php
if ($this->form->getAdjunto()->count()):
    $finfo = new finfo(FILEINFO_MIME_TYPE);
    $sumsize = 0;
    $urlDescargar = array('controller' => 'archivo', 'action' => 'descargar');
    foreach ($this->form->getAdjunto() as $index => $archivo):
        $eSeleccion = $this->form->getElement(Application_Form_SolicitudAdjunto::E_SELECCION . '_' . $archivo->id);
        $filename = $archivo->ruta . DIRECTORY_SEPARATOR . $archivo->id;
        $existe = is_readable($filename);
        if ($existe):
            $size = filesize($filename);
            $mime = $finfo->file($filename);
        else:
            $eSeleccion->addError('Archivo inexistente o ilegible');
            $size = 0;
            $mime = '';            
        endif;
        $sumsize += $size;
?>        
        <tr>
            <td align="right"><?php echo $index + 1, $eSeleccion->renderViewHelper(); ?></td>
            <td><?php 
        if ($existe):
            $urlDescargar['id'] = $archivo->id;    
            echo '<a href="', $this->url($urlDescargar), '" title="Descargar archivo...">', $this->escape($archivo->nombre), '</a>';
        else:    
            echo $this->escape($archivo->nombre);
        endif;        
        echo $eSeleccion->renderDescription(), 
             $this->form->getElement(Application_Form_SolicitudAdjunto::E_SELECCION)->renderErrors(), 
             $eSeleccion->renderErrors(); ?></td>
            <td align="right"><?php echo Fmo_Util::binaryToString($size); ?></td>
            <td align="center"><?php echo $this->escape($mime); ?></td>
            <td align="center"><?php echo Fmo_Util::stringToZendDate($archivo->fecha_registro); ?></td>
        </tr>
<?php
    endforeach;
?>
        <tr>
            <th align="right" colspan="2">Total</th>
            <td align="right"><b><?php echo Fmo_Util::binaryToString($sumsize); ?></b></td>
            <th colspan="2"></th>
        </tr>
<?php
else:
?>
        <tr>
            <td align="center" colspan="5">Disculpe, la consulta no devolvió registros.</td>
        </tr>
<?php
endif;
?>
    </tbody>
</table>
<?php
echo '</form>', PHP_EOL;
?>
<br/>